version: 2.1
jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.0
      - image: circleci/postgres
        environment:
          RAILS_ENV: test
          CC_TEST_REPORTER_ID: 6e79dd9d7ed2346892fa600d2f911f603e18b825d4d33b9d0de5eea1be3f5e5d
          POSTGRES_HOST: localhost
          POSTGRES_DATABASE: circle_test
          POSTGRES_USER: circleci
          POSTGRES_PASSWORD: circleci
    steps:
      - checkout
      - run: mv .env.ci .env
      - run: sudo apt-get update
      - run: echo 'export PATH=/usr/lib/postgresql/12/bin/:$PATH' >> $BASH_ENV
      - run:
          name: install dependencies
          environment:
            BUNDLE_PATH: vendor/bundle
          command: |
            bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3 && bundle clean
      - run:
          name:  Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run: bundle exec rails db:create
      - run: bundle exec rails db:migrate      
      - run:
          name: run RSpec
          command: |
            bundle exec rspec 
            ./cc-test-reporter format-coverage -t simplecov -o codeclimate.json coverage/.resultset.json
      - persist_to_workspace:
          root: ./
          paths: codeclimate.json
      - run: cat codeclimate.json
      
workflows:
  main:
    jobs:
      - build