version: 2.1
jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.0-node
    steps:
      - checkout
      - run: ruby --version
      - run:
          name: install dependencies
          environment:
            BUNDLE_PATH: vendor/bundle
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle && bundle clean
      - run: bundle exec rails --version
      - run:
          name: run RSpec
          command: bundle exec rspec