version: 2.1
jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.0
      - image: circleci/postgres
        environment:
          RAILS_ENV: test
          CC_TEST_REPORTER_ID: 6e79dd9d7ed2346892fa600d2f911f603e18b825d4d33b9d0de5eea1be3f5e5d
          POSTGRESQL_HOST: localhost
          POSTGRESQL_DATABASE: circle_test
          POSTGRESQL_USER: circleci
          POSTGRESQL_PASSWORD: circleci
          
    steps:
      - checkout
      - run: sudo apt-get update
      - run: echo 'export PATH=/usr/lib/postgresql/14.1/bin/:$PATH' >> $BASH_ENV
      - run:
          name: install dependencies
          environment:
            BUNDLE_PATH: vendor/bundle
          command: |
            bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3 && bundle clean
      - run:
          name:  Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: run RSpec
          command: |
            ./cc-test-reporter before-build
            mkdir test_results
            bundle exec rspec --format documentation --format RspecJunitFormatter --out test_results/rspec/rspec.xml
            ./cc-test-reporter after-build --coverage-input-type simplecov  --exit-code $?

