default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["POSTGRESQL_HOST"] %>
  username: <%= ENV["POSTGRESQL_USER"] %>
  password: <%= ENV["POSTGRESQL_PASSWORD"] %>
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_api_interview_template_development

test:
  <<: *default
  database: <%= ENV["POSTGRESQL_DATABASE"] %>
